var test_stimuli = [
  {
    "item_id": 0,
    "verb": "bake",
    "verb_participle": "baking",
    "object": "a cake",
    "prep": "inside",
    "classification_prefix": "baking a cake inside",
    "binary_prefix": "Could someone bake a cake inside",
    "sentence_prefix": "[NP] baked a cake inside",
    "probable": "an oven",
    "improbable": "an airfryer",
    "impossible": "a freezer",
    "inconceivable": "a sigh"
  },
  {
    "item_id": 1,
    "verb": "boil",
    "verb_participle": "boiling",
    "object": "water",
    "prep": "using",
    "classification_prefix": "boiling water using",
    "binary_prefix": "Could someone boil water using",
    "sentence_prefix": "[NP] boiled water using",
    "probable": "a kettle",
    "improbable": "a microwave",
    "impossible": "a refrigerator",
    "inconceivable": "justice"
  },
  {
    "item_id": 2,
    "verb": "break",
    "verb_participle": "breaking",
    "object": "a coconut",
    "prep": "using",
    "classification_prefix": "breaking a coconut using",
    "binary_prefix": "Could someone break a coconut using",
    "sentence_prefix": "[NP] broke a coconut using",
    "probable": "a rock",
    "improbable": "a table",
    "impossible": "a pillow",
    "inconceivable": "a texture"
  },
  {
    "item_id": 3,
    "verb": "build",
    "verb_participle": "building",
    "object": "a house",
    "prep": "out of",
    "classification_prefix": "building a house out of",
    "binary_prefix": "Could someone build a house out of",
    "sentence_prefix": "[NP] built a house out of",
    "probable": "brick",
    "improbable": "grass",
    "impossible": "gas",
    "inconceivable": "language"
  },
  {
    "item_id": 4,
    "verb": "build",
    "verb_participle": "building",
    "object": "a bridge",
    "prep": "out of",
    "classification_prefix": "building a bridge out of",
    "binary_prefix": "Could someone build a bridge out of",
    "sentence_prefix": "[NP] built a bridge out of",
    "probable": "steel",
    "improbable": "plastic",
    "impossible": "soup",
    "inconceivable": "dance"
  },
  {
    "item_id": 5,
    "verb": "call",
    "verb_participle": "calling",
    "object": "a friend",
    "prep": "using",
    "classification_prefix": "calling a friend using",
    "binary_prefix": "Could someone call a friend using",
    "sentence_prefix": "[NP] called a friend using",
    "probable": "a phone",
    "improbable": "a laptop",
    "impossible": "a sandwich",
    "inconceivable": "mass"
  },
  {
    "item_id": 6,
    "verb": "carry",
    "verb_participle": "carrying",
    "object": "groceries",
    "prep": "inside",
    "classification_prefix": "carrying groceries inside",
    "binary_prefix": "Could someone carry groceries inside",
    "sentence_prefix": "[NP] carried groceries inside",
    "probable": "a tote bag",
    "improbable": "a backpack",
    "impossible": "a tornado",
    "inconceivable": "a law"
  },
  {
    "item_id": 7,
    "verb": "carve",
    "verb_participle": "carving",
    "object": "a statue",
    "prep": "using",
    "classification_prefix": "carving a statue using",
    "binary_prefix": "Could someone carve a statue using",
    "sentence_prefix": "[NP] carved a statue using",
    "probable": "a chisel",
    "improbable": "a nail",
    "impossible": "a sock",
    "inconceivable": "laughter"
  },
  {
    "item_id": 8,
    "verb": "catch",
    "verb_participle": "catching",
    "object": "a fish",
    "prep": "in",
    "classification_prefix": "catching a fish in",
    "binary_prefix": "Could someone catch a fish in",
    "sentence_prefix": "[NP] caught a fish in",
    "probable": "a lake",
    "improbable": "a puddle",
    "impossible": "a raindrop",
    "inconceivable": "an exclamation"
  },
  {
    "item_id": 9,
    "verb": "chill",
    "verb_participle": "chilling",
    "object": "a drink",
    "prep": "using",
    "classification_prefix": "chilling a drink using",
    "binary_prefix": "Could someone chill a drink using",
    "sentence_prefix": "[NP] chilled a drink using",
    "probable": "ice",
    "improbable": "snow",
    "impossible": "fire",
    "inconceivable": "yesterday"
  },
  {
    "item_id": 10,
    "verb": "chop",
    "verb_participle": "chopping",
    "object": "a carrot",
    "prep": "using",
    "classification_prefix": "chopping a carrot using",
    "binary_prefix": "Could someone chop a carrot using",
    "sentence_prefix": "[NP] chopped a carrot using",
    "probable": "a knife",
    "improbable": "a sword",
    "impossible": "a rag",
    "inconceivable": "a color"
  },
  {
    "item_id": 11,
    "verb": "clean",
    "verb_participle": "cleaning",
    "object": "a spill",
    "prep": "using",
    "classification_prefix": "cleaning a spill using",
    "binary_prefix": "Could someone clean a spill using",
    "sentence_prefix": "[NP] cleaned a spill using",
    "probable": "a sponge",
    "improbable": "a scarf",
    "impossible": "mustard",
    "inconceivable": "a country"
  },
  {
    "item_id": 12,
    "verb": "clean",
    "verb_participle": "cleaning",
    "object": "a carpet",
    "prep": "using",
    "classification_prefix": "cleaning a carpet using",
    "binary_prefix": "Could someone clean a carpet using",
    "sentence_prefix": "[NP] cleaned a carpet using",
    "probable": "a vacuum",
    "improbable": "a hat",
    "impossible": "a crayon",
    "inconceivable": "a week"
  },
  {
    "item_id": 13,
    "verb": "climb",
    "verb_participle": "climbing",
    "object": "a tree",
    "prep": "using",
    "classification_prefix": "climbing a tree using",
    "binary_prefix": "Could someone climb a tree using",
    "sentence_prefix": "[NP] climbed a tree using",
    "probable": "a ladder",
    "improbable": "a rope",
    "impossible": "oil",
    "inconceivable": "a poem"
  },
  {
    "item_id": 14,
    "verb": "close",
    "verb_participle": "closing",
    "object": "a jacket",
    "prep": "using",
    "classification_prefix": "closing a jacket using",
    "binary_prefix": "Could someone close a jacket using",
    "sentence_prefix": "[NP] closed a jacket using",
    "probable": "a zipper",
    "improbable": "glue",
    "impossible": "fog",
    "inconceivable": "a word"
  },
  {
    "item_id": 15,
    "verb": "construct",
    "verb_participle": "constructing",
    "object": "a tower",
    "prep": "out of",
    "classification_prefix": "constructing a tower out of",
    "binary_prefix": "Could someone construct a tower out of",
    "sentence_prefix": "[NP] constructed a tower out of",
    "probable": "blocks",
    "improbable": "bubbles",
    "impossible": "sparks",
    "inconceivable": "seasons"
  },
  {
    "item_id": 16,
    "verb": "cook",
    "verb_participle": "cooking",
    "object": "dinner",
    "prep": "out of",
    "classification_prefix": "cooking dinner out of",
    "binary_prefix": "Could someone cook dinner out of",
    "sentence_prefix": "[NP] cooked dinner out of",
    "probable": "pasta",
    "improbable": "insects",
    "impossible": "the moon",
    "inconceivable": "thoughts"
  },
  {
    "item_id": 17,
    "verb": "cool",
    "verb_participle": "cooling",
    "object": "a room",
    "prep": "using",
    "classification_prefix": "cooling a room using",
    "binary_prefix": "Could someone cool a room using",
    "sentence_prefix": "[NP] cooled a room using",
    "probable": "a fan",
    "improbable": "shades",
    "impossible": "a heater",
    "inconceivable": "a taste"
  },
  {
    "item_id": 18,
    "verb": "cover",
    "verb_participle": "covering",
    "object": "a window",
    "prep": "using",
    "classification_prefix": "covering a window using",
    "binary_prefix": "Could someone cover a window using",
    "sentence_prefix": "[NP] covered a window using",
    "probable": "curtains",
    "improbable": "sheets",
    "impossible": "a hair",
    "inconceivable": "a chant"
  },
  {
    "item_id": 19,
    "verb": "craft",
    "verb_participle": "crafting",
    "object": "a bowl",
    "prep": "out of",
    "classification_prefix": "crafting a bowl out of",
    "binary_prefix": "Could someone craft a bowl out of",
    "sentence_prefix": "[NP] crafted a bowl out of",
    "probable": "clay",
    "improbable": "mud",
    "impossible": "smoke",
    "inconceivable": "math"
  },
  {
    "item_id": 20,
    "verb": "crush",
    "verb_participle": "crushing",
    "object": "a soda can",
    "prep": "using",
    "classification_prefix": "crushing a soda can using",
    "binary_prefix": "Could someone crush a soda can using",
    "sentence_prefix": "[NP] crushed a soda can using",
    "probable": "a shoe",
    "improbable": "a chair",
    "impossible": "a tissue",
    "inconceivable": "a day"
  },
  {
    "item_id": 21,
    "verb": "cut",
    "verb_participle": "cutting",
    "object": "grass",
    "prep": "using",
    "classification_prefix": "cutting grass using",
    "binary_prefix": "Could someone cut grass using",
    "sentence_prefix": "[NP] cut grass using",
    "probable": "a lawnmower",
    "improbable": "a scythe",
    "impossible": "a popsicle",
    "inconceivable": "an essay"
  },
  {
    "item_id": 22,
    "verb": "cut",
    "verb_participle": "cutting",
    "object": "cardboard",
    "prep": "using",
    "classification_prefix": "cutting cardboard using",
    "binary_prefix": "Could someone cut cardboard using",
    "sentence_prefix": "[NP] cut cardboard using",
    "probable": "scissors",
    "improbable": "a scalpel",
    "impossible": "fur",
    "inconceivable": "a snore"
  },
  {
    "item_id": 23,
    "verb": "dent",
    "verb_participle": "denting",
    "object": "a car",
    "prep": "with",
    "classification_prefix": "denting a car with",
    "binary_prefix": "Could someone dent a car with",
    "sentence_prefix": "[NP] dented a car with",
    "probable": "a baseball bat",
    "improbable": "a dumbbell",
    "impossible": "a breeze",
    "inconceivable": "a nap"
  },
  {
    "item_id": 24,
    "verb": "dig",
    "verb_participle": "digging",
    "object": "a hole",
    "prep": "using",
    "classification_prefix": "digging a hole using",
    "binary_prefix": "Could someone dig a hole using",
    "sentence_prefix": "[NP] dug a hole using",
    "probable": "a shovel",
    "improbable": "a spatula",
    "impossible": "dirt",
    "inconceivable": "a yawn"
  },
  {
    "item_id": 25,
    "verb": "dip",
    "verb_participle": "dipping",
    "object": "a biscuit",
    "prep": "into",
    "classification_prefix": "dipping a biscuit into",
    "binary_prefix": "Could someone dip a biscuit into",
    "sentence_prefix": "[NP] dipped a biscuit into",
    "probable": "coffee",
    "improbable": "wine",
    "impossible": "a floor",
    "inconceivable": "a myth"
  },
  {
    "item_id": 26,
    "verb": "display",
    "verb_participle": "displaying",
    "object": "books",
    "prep": "on",
    "classification_prefix": "displaying books on",
    "binary_prefix": "Could someone display books on",
    "sentence_prefix": "[NP] displayed books on",
    "probable": "a shelf",
    "improbable": "a bed",
    "impossible": "a galaxy",
    "inconceivable": "a sigh"
  },
  {
    "item_id": 27,
    "verb": "dock",
    "verb_participle": "docking",
    "object": "a boat",
    "prep": "using",
    "classification_prefix": "docking a boat using",
    "binary_prefix": "Could someone dock a boat using",
    "sentence_prefix": "[NP] docked a boat using",
    "probable": "an anchor",
    "improbable": "an anvil",
    "impossible": "a balloon",
    "inconceivable": "a lesson"
  },
  {
    "item_id": 28,
    "verb": "drink",
    "verb_participle": "drinking",
    "object": "a cup",
    "prep": "full of",
    "classification_prefix": "drinking a cup full of",
    "binary_prefix": "Could someone drink a cup full of",
    "sentence_prefix": "[NP] drank a cup full of",
    "probable": "water",
    "improbable": "honey",
    "impossible": "lightning",
    "inconceivable": "minutes"
  },
  {
    "item_id": 29,
    "verb": "dry",
    "verb_participle": "drying",
    "object": "[POSS] hands",
    "prep": "using",
    "classification_prefix": "drying [POSS] hands using",
    "binary_prefix": "Could someone dry [POSS] hands using",
    "sentence_prefix": "[NP] dried [POSS] hands using",
    "probable": "a towel",
    "improbable": "a sweater",
    "impossible": "a liquid",
    "inconceivable": "freedom"
  },
  {
    "item_id": 30,
    "verb": "dry",
    "verb_participle": "drying",
    "object": "laundry",
    "prep": "using",
    "classification_prefix": "drying laundry using",
    "binary_prefix": "Could someone dry laundry using",
    "sentence_prefix": "[NP] dried laundry using",
    "probable": "a clothesline",
    "improbable": "a fan",
    "impossible": "juice",
    "inconceivable": "courage"
  },
  {
    "item_id": 31,
    "verb": "eat",
    "verb_participle": "eating",
    "object": "soup",
    "prep": "using",
    "classification_prefix": "eating soup using",
    "binary_prefix": "Could someone eat soup using",
    "sentence_prefix": "[NP] ate soup using",
    "probable": "a spoon",
    "improbable": "a bucket",
    "impossible": "a sieve",
    "inconceivable": "history"
  },
  {
    "item_id": 32,
    "verb": "enter",
    "verb_participle": "entering",
    "object": "a room",
    "prep": "through",
    "classification_prefix": "entering a room through",
    "binary_prefix": "Could someone enter a room through",
    "sentence_prefix": "[NP] entered a room through",
    "probable": "a door",
    "improbable": "a window",
    "impossible": "a wall",
    "inconceivable": "a theory"
  },
  {
    "item_id": 33,
    "verb": "fill",
    "verb_participle": "filling",
    "object": "a bucket",
    "prep": "with",
    "classification_prefix": "filling a bucket with",
    "binary_prefix": "Could someone fill a bucket with",
    "sentence_prefix": "[NP] filled a bucket with",
    "probable": "sand",
    "improbable": "acorns",
    "impossible": "buildings",
    "inconceivable": "time"
  },
  {
    "item_id": 34,
    "verb": "fill",
    "verb_participle": "filling",
    "object": "a purse",
    "prep": "with",
    "classification_prefix": "filling a purse with",
    "binary_prefix": "Could someone fill a purse with",
    "sentence_prefix": "[NP] filled a purse with",
    "probable": "coins",
    "improbable": "cream",
    "impossible": "sofas",
    "inconceivable": "luck"
  },
  {
    "item_id": 35,
    "verb": "grow",
    "verb_participle": "growing",
    "object": "flowers",
    "prep": "inside",
    "classification_prefix": "growing flowers inside",
    "binary_prefix": "Could someone grow flowers inside",
    "sentence_prefix": "[NP] grew flowers inside",
    "probable": "a pot",
    "improbable": "a mug",
    "impossible": "a marble",
    "inconceivable": "a sneeze"
  },
  {
    "item_id": 36,
    "verb": "hang",
    "verb_participle": "hanging",
    "object": "a painting",
    "prep": "using",
    "classification_prefix": "hanging a painting using",
    "binary_prefix": "Could someone hang a painting using",
    "sentence_prefix": "[NP] hung a painting using",
    "probable": "screws",
    "improbable": "string",
    "impossible": "vapor",
    "inconceivable": "a handshake"
  },
  {
    "item_id": 37,
    "verb": "hide",
    "verb_participle": "hiding",
    "object": "a gift",
    "prep": "inside",
    "classification_prefix": "hiding a gift inside",
    "binary_prefix": "Could someone hide a gift inside",
    "sentence_prefix": "[NP] hid a gift inside",
    "probable": "a closet",
    "improbable": "a forest",
    "impossible": "a cloud",
    "inconceivable": "a gasp"
  },
  {
    "item_id": 38,
    "verb": "lift",
    "verb_participle": "lifting",
    "object": "a box",
    "prep": "using",
    "classification_prefix": "lifting a box using",
    "binary_prefix": "Could someone lift a box using",
    "sentence_prefix": "[NP] lifted a box using",
    "probable": "a forklift",
    "improbable": "a pulley",
    "impossible": "foam",
    "inconceivable": "an emotion"
  },
  {
    "item_id": 39,
    "verb": "light",
    "verb_participle": "lighting",
    "object": "a candle",
    "prep": "using",
    "classification_prefix": "lighting a candle using",
    "binary_prefix": "Could someone light a candle using",
    "sentence_prefix": "[NP] lit a candle using",
    "probable": "a match",
    "improbable": "a blowtorch",
    "impossible": "yogurt",
    "inconceivable": "surprises"
  },
  {
    "item_id": 40,
    "verb": "make",
    "verb_participle": "making",
    "object": "a sandwich",
    "prep": "using",
    "classification_prefix": "making a sandwich using",
    "binary_prefix": "Could someone make a sandwich using",
    "sentence_prefix": "[NP] made a sandwich using",
    "probable": "bread",
    "improbable": "lettuce",
    "impossible": "a star",
    "inconceivable": "a mile"
  },
  {
    "item_id": 41,
    "verb": "make",
    "verb_participle": "making",
    "object": "a smoothie",
    "prep": "using",
    "classification_prefix": "making a smoothie using",
    "binary_prefix": "Could someone make a smoothie using",
    "sentence_prefix": "[NP] made a smoothie using",
    "probable": "a blender",
    "improbable": "a whisk",
    "impossible": "wind",
    "inconceivable": "decades"
  },
  {
    "item_id": 42,
    "verb": "melt",
    "verb_participle": "melting",
    "object": "a chocolate bar",
    "prep": "using",
    "classification_prefix": "melting a chocolate bar using",
    "binary_prefix": "Could someone melt a chocolate bar using",
    "sentence_prefix": "[NP] melted a chocolate bar using",
    "probable": "a stove",
    "improbable": "a radiator",
    "impossible": "a napkin",
    "inconceivable": "a promise"
  },
  {
    "item_id": 43,
    "verb": "open",
    "verb_participle": "opening",
    "object": "a jar",
    "prep": "using",
    "classification_prefix": "opening a jar using",
    "binary_prefix": "Could someone open a jar using",
    "sentence_prefix": "[NP] opened a jar using",
    "probable": "[POSS] hands",
    "improbable": "[POSS] feet",
    "impossible": "[POSS] mind",
    "inconceivable": "an opinion"
  },
  {
    "item_id": 44,
    "verb": "pack",
    "verb_participle": "packing",
    "object": "a suit",
    "prep": "inside",
    "classification_prefix": "packing a suit inside",
    "binary_prefix": "Could someone pack a suit inside",
    "sentence_prefix": "[NP] packed a suit inside",
    "probable": "a suitcase",
    "improbable": "a pocket",
    "impossible": "a raspberry",
    "inconceivable": "a groan"
  },
  {
    "item_id": 45,
    "verb": "paint",
    "verb_participle": "painting",
    "object": "a wall",
    "prep": "using",
    "classification_prefix": "painting a wall using",
    "binary_prefix": "Could someone paint a wall using",
    "sentence_prefix": "[NP] painted a wall using",
    "probable": "a brush",
    "improbable": "a mop",
    "impossible": "a bathtub",
    "inconceivable": "a whisper"
  },
  {
    "item_id": 46,
    "verb": "pave",
    "verb_participle": "paving",
    "object": "a road",
    "prep": "using",
    "classification_prefix": "paving a road using",
    "binary_prefix": "Could someone pave a road using",
    "sentence_prefix": "[NP] paved a road using",
    "probable": "cement",
    "improbable": "seashells",
    "impossible": "a comet",
    "inconceivable": "happiness"
  },
  {
    "item_id": 47,
    "verb": "pluck",
    "verb_participle": "plucking",
    "object": "a hair",
    "prep": "using",
    "classification_prefix": "plucking a hair using",
    "binary_prefix": "Could someone pluck a hair using",
    "sentence_prefix": "[NP] plucked a hair using",
    "probable": "tweezers",
    "improbable": "tongs",
    "impossible": "a spoon",
    "inconceivable": "sympathy"
  },
  {
    "item_id": 48,
    "verb": "polish",
    "verb_participle": "polishing",
    "object": "jewelry",
    "prep": "using",
    "classification_prefix": "polishing jewelry using",
    "binary_prefix": "Could someone polish jewelry using",
    "sentence_prefix": "[NP] polished jewelry using",
    "probable": "a cloth",
    "improbable": "a shirt",
    "impossible": "a chainsaw",
    "inconceivable": "music"
  },
  {
    "item_id": 49,
    "verb": "pop",
    "verb_participle": "popping",
    "object": "a balloon",
    "prep": "using",
    "classification_prefix": "popping a balloon using",
    "binary_prefix": "Could someone pop a balloon using",
    "sentence_prefix": "[NP] popped a balloon using",
    "probable": "a thumbtack",
    "improbable": "a spear",
    "impossible": "cotton balls",
    "inconceivable": "a story"
  },
  {
    "item_id": 50,
    "verb": "remove",
    "verb_participle": "removing",
    "object": "a stain",
    "prep": "using",
    "classification_prefix": "removing a stain using",
    "binary_prefix": "Could someone remove a stain using",
    "sentence_prefix": "[NP] removed a stain using",
    "probable": "bleach",
    "improbable": "vinegar",
    "impossible": "dirt",
    "inconceivable": "truth"
  },
  {
    "item_id": 51,
    "verb": "rinse",
    "verb_participle": "rinsing",
    "object": "fruit",
    "prep": "using",
    "classification_prefix": "rinsing fruit using",
    "binary_prefix": "Could someone rinse fruit using",
    "sentence_prefix": "[NP] rinsed fruit using",
    "probable": "a sink",
    "improbable": "a hose",
    "impossible": "a clock",
    "inconceivable": "a giggle"
  },
  {
    "item_id": 52,
    "verb": "sew",
    "verb_participle": "sewing",
    "object": "a shirt",
    "prep": "using",
    "classification_prefix": "sewing a shirt using",
    "binary_prefix": "Could someone sew a shirt using",
    "sentence_prefix": "[NP] sewed a shirt using",
    "probable": "a needle",
    "improbable": "a toothpick",
    "impossible": "a potato",
    "inconceivable": "thunder"
  },
  {
    "item_id": 53,
    "verb": "shatter",
    "verb_participle": "shattering",
    "object": "a window",
    "prep": "using",
    "classification_prefix": "shattering a window using",
    "binary_prefix": "Could someone shatter a window using",
    "sentence_prefix": "[NP] shattered a window using",
    "probable": "a stone",
    "improbable": "a frisbee",
    "impossible": "confetti",
    "inconceivable": "a concept"
  },
  {
    "item_id": 54,
    "verb": "shave",
    "verb_participle": "shaving",
    "object": "[POSS] beard",
    "prep": "using",
    "classification_prefix": "shaving [POSS] beard using",
    "binary_prefix": "Could someone shave [POSS] beard using",
    "sentence_prefix": "[NP] shaved [POSS] beard using",
    "probable": "a razor",
    "improbable": "a knife",
    "impossible": "a teabag",
    "inconceivable": "a belief"
  },
  {
    "item_id": 55,
    "verb": "smash",
    "verb_participle": "smashing",
    "object": "a pumpkin",
    "prep": "using",
    "classification_prefix": "smashing a pumpkin using",
    "binary_prefix": "Could someone smash a pumpkin using",
    "sentence_prefix": "[NP] smashed a pumpkin using",
    "probable": "a hammer",
    "improbable": "a boulder",
    "impossible": "a leaf",
    "inconceivable": "a number"
  },
  {
    "item_id": 56,
    "verb": "split",
    "verb_participle": "splitting",
    "object": "a log",
    "prep": "using",
    "classification_prefix": "splitting a log using",
    "binary_prefix": "Could someone split a log using",
    "sentence_prefix": "[NP] split a log using",
    "probable": "an axe",
    "improbable": "a saw",
    "impossible": "a feather",
    "inconceivable": "a gasp"
  },
  {
    "item_id": 57,
    "verb": "squeeze",
    "verb_participle": "squeezing",
    "object": "juice",
    "prep": "from",
    "classification_prefix": "squeezing juice from",
    "binary_prefix": "Could someone squeeze juice from",
    "sentence_prefix": "[NP] squeezed juice from",
    "probable": "an orange",
    "improbable": "meat",
    "impossible": "an envelope",
    "inconceivable": "a mumble"
  },
  {
    "item_id": 58,
    "verb": "squish",
    "verb_participle": "squishing",
    "object": "a blueberry",
    "prep": "using",
    "classification_prefix": "squishing a blueberry using",
    "binary_prefix": "Could someone squish a blueberry using",
    "sentence_prefix": "[NP] squished a blueberry using",
    "probable": "[POSS] finger",
    "improbable": "[POSS] nose",
    "impossible": "[POSS] breath",
    "inconceivable": "a sight"
  },
  {
    "item_id": 59,
    "verb": "start",
    "verb_participle": "starting",
    "object": "a fire",
    "prep": "using",
    "classification_prefix": "starting a fire using",
    "binary_prefix": "Could someone start a fire using",
    "sentence_prefix": "[NP] started a fire using",
    "probable": "kindling",
    "improbable": "furniture",
    "impossible": "milk",
    "inconceivable": "humor"
  },
  {
    "item_id": 60,
    "verb": "store",
    "verb_participle": "storing",
    "object": "dishes",
    "prep": "inside",
    "classification_prefix": "storing dishes inside",
    "binary_prefix": "Could someone store dishes inside",
    "sentence_prefix": "[NP] stored dishes inside",
    "probable": "a cabinet",
    "improbable": "an attic",
    "impossible": "a thimble",
    "inconceivable": "an equation"
  },
  {
    "item_id": 61,
    "verb": "take",
    "verb_participle": "taking",
    "object": "a vacation",
    "prep": "to",
    "classification_prefix": "taking a vacation to",
    "binary_prefix": "Could someone take a vacation to",
    "sentence_prefix": "[NP] took a vacation to",
    "probable": "the beach",
    "improbable": "the desert",
    "impossible": "the sun",
    "inconceivable": "a verb"
  },
  {
    "item_id": 62,
    "verb": "tighten",
    "verb_participle": "tightening",
    "object": "a bolt",
    "prep": "using",
    "classification_prefix": "tightening a bolt using",
    "binary_prefix": "Could someone tighten a bolt using",
    "sentence_prefix": "[NP] tightened a bolt using",
    "probable": "a wrench",
    "improbable": "chopsticks",
    "impossible": "a house",
    "inconceivable": "a dream"
  },
  {
    "item_id": 63,
    "verb": "turn",
    "verb_participle": "turning",
    "object": "an apple",
    "prep": "into",
    "classification_prefix": "turning an apple into",
    "binary_prefix": "Could someone turn an apple into",
    "sentence_prefix": "[NP] turned an apple into",
    "probable": "a pie",
    "improbable": "a salad",
    "impossible": "a cherry",
    "inconceivable": "honesty"
  },
  {
    "item_id": 64,
    "verb": "unlock",
    "verb_participle": "unlocking",
    "object": "a door",
    "prep": "using",
    "classification_prefix": "unlocking a door using",
    "binary_prefix": "Could someone unlock a door using",
    "sentence_prefix": "[NP] unlocked a door using",
    "probable": "a key",
    "improbable": "a screwdriver",
    "impossible": "a marshmallow",
    "inconceivable": "a lie"
  },
  {
    "item_id": 65,
    "verb": "wash",
    "verb_participle": "washing",
    "object": "[POSS] hair",
    "prep": "using",
    "classification_prefix": "washing [POSS] hair using",
    "binary_prefix": "Could someone wash [POSS] hair using",
    "sentence_prefix": "[NP] washed [POSS] hair using",
    "probable": "shampoo",
    "improbable": "detergent",
    "impossible": "a rainbow",
    "inconceivable": "applause"
  },
  {
    "item_id": 66,
    "verb": "wear",
    "verb_participle": "wearing",
    "object": "shoes",
    "prep": "made of",
    "classification_prefix": "wearing shoes made of",
    "binary_prefix": "Could someone wear shoes made of",
    "sentence_prefix": "[NP] wore shoes made of",
    "probable": "leather",
    "improbable": "wood",
    "impossible": "stars",
    "inconceivable": "traffic"
  },
  {
    "item_id": 67,
    "verb": "wrap",
    "verb_participle": "wrapping",
    "object": "a present",
    "prep": "using",
    "classification_prefix": "wrapping a present using",
    "binary_prefix": "Could someone wrap a present using",
    "sentence_prefix": "[NP] wrapped a present using",
    "probable": "paper",
    "improbable": "a dress",
    "impossible": "ketchup",
    "inconceivable": "gossip"
  },
  {
    "item_id": 68,
    "verb": "write",
    "verb_participle": "writing",
    "object": "a letter",
    "prep": "using",
    "classification_prefix": "writing a letter using",
    "binary_prefix": "Could someone write a letter using",
    "sentence_prefix": "[NP] wrote a letter using",
    "probable": "a pen",
    "improbable": "a stylus",
    "impossible": "a snowflake",
    "inconceivable": "a marathon"
  },
  {
    "item_id": 69,
    "verb": "write",
    "verb_participle": "writing",
    "object": "an equation",
    "prep": "on",
    "classification_prefix": "writing an equation on",
    "binary_prefix": "Could someone write an equation on",
    "sentence_prefix": "[NP] wrote an equation on",
    "probable": "a chalkboard",
    "improbable": "a billboard",
    "impossible": "an atom",
    "inconceivable": "a scream"
  }
]